
def create_codebook(tl_metadata):
    layers = tl_metadata["layers"]

    codebook = {
        "addr": {
            "type": layers["addr"]["type"],
            "file": layers["addr"]["file"],
            "scale": layers["addr"]["scale"],
            "spatial": layers["addr"]["spatial"],
            "abbrev": layers["addr"]["abbrev"],
            "postfix": layers["addr"]["postfix"],
            "postfix_desc": layers["addr"]["postfix_desc"],
            "alias": "Address Ranges",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Address Ranges Relationship File",
            "code": "AD",
            "method": "none",
        },
        "addrfeat": {
            "type": layers["addrfeat"]["type"],
            "file": layers["addrfeat"]["file"],
            "scale": layers["addrfeat"]["scale"],
            "spatial": layers["addrfeat"]["spatial"],
            "abbrev": layers["addrfeat"]["abbrev"],
            "postfix": layers["addrfeat"]["postfix"],
            "postfix_desc": layers["addrfeat"]["postfix_desc"],
            "alias": "Address Range Features",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Address Range Feature Shapefile",
            "code": "AF",
            "method": "copy",
        },
        "addrfn": {
            "type": layers["addrfn"]["type"],
            "file": layers["addrfn"]["file"],
            "scale": layers["addrfn"]["scale"],
            "spatial": layers["addrfn"]["spatial"],
            "abbrev": layers["addrfn"]["abbrev"],
            "postfix": layers["addrfn"]["postfix"],
            "postfix_desc": layers["addrfn"]["postfix_desc"],
            "alias": "Address Ranges Feature Names",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Address Range-Feature Name Relationship File",
            "code": "AN",
            "method": "none",
        },
        "areawater": {
            "type": layers["areawater"]["type"],
            "file": layers["areawater"]["file"],
            "scale": layers["areawater"]["scale"],
            "spatial": layers["areawater"]["spatial"],
            "abbrev": layers["areawater"]["abbrev"],
            "postfix": layers["areawater"]["postfix"],
            "postfix_desc": layers["areawater"]["postfix_desc"],
            "alias": "Area Hydrography",
            "group": "Features",
            "category": "Water",
            "label": "Area Hudrography",
            "code": "WA",
            "method": "copy",
        },
        "edges": {
            "type": layers["edges"]["type"],
            "file": layers["edges"]["file"],
            "scale": layers["edges"]["scale"],
            "spatial": layers["edges"]["spatial"],
            "abbrev": layers["edges"]["abbrev"],
            "postfix": layers["edges"]["postfix"],
            "postfix_desc": layers["edges"]["postfix_desc"],
            "alias": "All Lines",
            "group": "Features",
            "category": "All Lines",
            "label": "All Lines",
            "code": "ED",
            "method": "copy",
        },
        "faces": {
            "type": layers["faces"]["type"],
            "file": layers["faces"]["file"],
            "scale": layers["faces"]["scale"],
            "spatial": layers["faces"]["spatial"],
            "abbrev": layers["faces"]["abbrev"],
            "postfix": layers["faces"]["postfix"],
            "postfix_desc": layers["faces"]["postfix_desc"],
            "alias": "Topological Faces",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Topological Faces (Polygons with all Geocodes) Shapefile",
            "code": "FC",
            "method": "copy",
        },
        "facesah": {
            "type": layers["facesah"]["type"],
            "file": layers["facesah"]["file"],
            "scale": layers["facesah"]["scale"],
            "spatial": layers["facesah"]["spatial"],
            "abbrev": layers["facesah"]["abbrev"],
            "postfix": layers["facesah"]["postfix"],
            "postfix_desc": layers["facesah"]["postfix_desc"],
            "alias": "Topological Faces-Area Hydrography",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Topological Faces-Area Hydrography Relationship File",
            "code": "FH",
            "method": "none",
        },
    }