# Import necessary libraries
import os, sys, datetime
from pathlib import Path
import shutil
import pandas as pd
import arcpy
from arcgis.features import GeoAccessor, GeoSeriesAccessor
from octl import OCTL

# Set pandas options
pd.options.mode.copy_on_write = True

# Set environment workspace to the current working directory
arcpy.env.workspace = os.getcwd()
arcpy.env.overwriteOutput = True

# Initialize the OCTL class object
octl = OCTL(part = 0, version = 2026.1)

# Get the project metadata and directories from the OCTL class object
prj_meta = octl.prj_meta
prj_dirs = octl.prj_dirs

# Get the codebook from the OCTL class object
cb = octl.cb
cbdf = octl.cbdf

# Get the raw data
tl_data = octl.tl_data

# Process the shapefiles and get the dictionary of feature classes and codes
tl_dict = octl.process_shapefiles()



def process_metadata():
    fc_metadata = {
        "06059_addr": {
            "abbrev": "ADDR",
            "alias":  f"OCTL {tl_data["year"]} Address Ranges",
            "type": "Table",
            "fcname": "AD",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Address Ranges Relationship File",
            "title": f"OCTL {tl_data["year"]} Address Ranges Relationship File Table",
            "tags": "Orange County, California, OCTL, TigerLines, Address, Relationships, Table",
            "summary": f"Orange County Tiger Lines {tl_data["year"]} Address Ranges Relationship File Table",
            "description": f"Orange County Tiger Lines {tl_data["year"]} Address Ranges Relationship File Table",
            "credits": "Dr. Kostas Alexandridis, GISP, Data Scientist, OC Public Works, OC Survey Geospatial Services",
            "access": """The feed data and associated resources (maps, apps, endpoints) can be used under a <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Creative Commons CC-SA-BY</a> License, providing attribution to OC Public Works, OC Survey Geospatial Services. <div><br /></div><div>We make every effort to provide the most accurate and up-to-date data and information. Nevertheless the data feed is provided, 'as is' and OC Public Work's standard <a href="https://www.ocgov.com/contact-county/disclaimer" target="_blank">Disclaimer</a> applies.</div><div><br /></div><div>For any inquiries, suggestions or questions, please contact:</div><div><br /></div><div style="text-align:center;"><a href="https://www.linkedin.com/in/ktalexan/" target="_blank"><b>Dr. Kostas Alexandridis, GISP</b></a><br /></div><div style="text-align:center;">GIS Analyst | Spatial Complex Systems Scientist</div><div style="text-align:center;">OC Public Works/OC Survey Geospatial Applications</div><div style="text-align:center;"><div>601 N. Ross Street, P.O. Box 4048, Santa Ana, CA 92701</div><div>Email: <a href="mailto:kostas.alexandridis@ocpw.ocgov.com" target="_blank">kostas.alexandridis@ocpw.ocgov.com</a> | Phone: (714) 967-0826</div></div>""",
            "uri": "https://ocpw.maps.arcgis.com/sharing/rest/content/items/20c4b722b7d84db3a4e163fc0ce11102/data"            
        },
        "06059_addrfeat": {
            "abbrev": "ADDRFEAT",
            "alias": f"OCTL {tl_data["year"]} Address Range Features",
            "type": "Feature Class",
            "fcname": "AF",
            "group": "Feature Relationships",
            "category": "Relationship Files",
            "label": "Address Range Feature Table",
            "title": f"OCTL {tl_data["year"]} Address Range Feature Class",
            "tags": "Orange County, California, OCTL, TigerLines, Address, Relationships, Feature Class",
            "summary": f"Orange County Tiger Lines {tl_data["year"]} Address Range Feature Class",
            "description": f"Orange County Tiger Lines {tl_data["year"]} Address Range Feature Class",
            "credits": "Dr. Kostas Alexandridis, GISP, Data Scientist, OC Public Works, OC Survey Geospatial Services",
            "access": """The feed data and associated resources (maps, apps, endpoints) can be used under a <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Creative Commons CC-SA-BY</a> License, providing attribution to OC Public Works, OC Survey Geospatial Services. <div><br /></div><div>We make every effort to provide the most accurate and up-to-date data and information. Nevertheless the data feed is provided, 'as is' and OC Public Work's standard <a href="https://www.ocgov.com/contact-county/disclaimer" target="_blank">Disclaimer</a> applies.</div><div><br /></div><div>For any inquiries, suggestions or questions, please contact:</div><div><br /></div><div style="text-align:center;"><a href="https://www.linkedin.com/in/ktalexan/" target="_blank"><b>Dr. Kostas Alexandridis, GISP</b></a><br /></div><div style="text-align:center;">GIS Analyst | Spatial Complex Systems Scientist</div><div style="text-align:center;">OC Public Works/OC Survey Geospatial Applications</div><div style="text-align:center;"><div>601 N. Ross Street, P.O. Box 4048, Santa Ana, CA 92701</div><div>Email: <a href="mailto:kostas.alexandridis@ocpw.ocgov.com" target="_blank">kostas.alexandridis@ocpw.ocgov.com</a> | Phone: (714) 967-0826</div></div>""",
            "uri": "https://ocpw.maps.arcgis.com/sharing/rest/content/items/20c4b722b7d84db3a4e163fc0ce11102/data"             
        },
        "06059_addrfn": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_areawater": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_edges": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_faces": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_facesah": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_featnames": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_linearwater": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06059_roads": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_arealm": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_bg": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_cd118": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_cd119": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_cousub": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_elsd": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_facesal": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_place": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_pointlm": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_prisecroads": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_puma20": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_scsd": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_sldl": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_sldu": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_tabblock20": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_tract": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "06_unsd": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_aitsn": {
            "abbrev": "AITSN",
            "alias": f"OCTL {tl_data['year']} Tribal Subdivisions",
            "type": "Shapefile",
            "fcname": "TS",
            "group": "Geographic Areas",
            "category": "American Indian Area Geography",
            "label": "American Indian Tribal Subdivision",
            "title": f"OCTL {tl_data['year']} Tribal Subdivisions Feature Class",
            "tags": "Orange County, California, OCTL, TigerLines, Tribal Subdivisions, American Indian Area Geography",
            "summary": f"Orange County Tiger Lines {tl_data['year']} Tribal Subdivisions Feature Class",
            "description" f"Orange County Tiger Lines {tl_data['year']} Tribal Subdivisions Feature Class",
            "credits": "Dr. Kostas Alexandridis, GISP, Data Scientist, OC Public Works, OC Survey Geospatial Services",
            "access": """The feed data and associated resources (maps, apps, endpoints) can be used under a <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Creative Commons CC-SA-BY</a> License, providing attribution to OC Public Works, OC Survey Geospatial Services. <div><br /></div><div>We make every effort to provide the most accurate and up-to-date data and information. Nevertheless the data feed is provided, 'as is' and OC Public Work's standard <a href="https://www.ocgov.com/contact-county/disclaimer" target="_blank">Disclaimer</a> applies.</div><div><br /></div><div>For any inquiries, suggestions or questions, please contact:</div><div><br /></div><div style="text-align:center;"><a href="https://www.linkedin.com/in/ktalexan/" target="_blank"><b>Dr. Kostas Alexandridis, GISP</b></a><br /></div><div style="text-align:center;">GIS Analyst | Spatial Complex Systems Scientist</div><div style="text-align:center;">OC Public Works/OC Survey Geospatial Applications</div><div style="text-align:center;"><div>601 N. Ross Street, P.O. Box 4048, Santa Ana, CA 92701</div><div>Email: <a href="mailto:kostas.alexandridis@ocpw.ocgov.com" target="_blank">kostas.alexandridis@ocpw.ocgov.com</a> | Phone: (714) 967-0826</div></div>""",
            "uri": "https://ocpw.maps.arcgis.com/sharing/rest/content/items/20c4b722b7d84db3a4e163fc0ce11102/data",
        },
        "us_cbsa": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri": 
        },
        "us_cd116": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_coastline": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_county": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_csa": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_facesmil": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_metdiv": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_mil": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_primaryroads": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_rails": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_tbg": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_ttract": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_uac20": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        },
        "us_zcta520": {
            "abbrev": ,
            "alias": ,
            "type": ,
            "fcname": ,
            "group": ,
            "category": ,
            "label": ,
            "title": ,
            "tags": ,
            "summary": ,
            "description": ,
            "credits": ,
            "access": ,
            "uri":             
        }
    }



list(cb.keys())


scratch_query_fcs = [f for f in scratch_fcs if cb[f.replace(f"tl_{tl_data['year']}_", "").replace(".shp", "")]["method"] == "query"]

for fc in scratch_query_fcs:
    code2 = cb[fc.replace(f"tl_{tl_data['year']}_", "").replace(".shp", "")]["code2"]
    arcpy.analysis.Select(
            in_features = os.path.join(scratch_gdb, fc),
            out_feature_class = os.path.join(tl_gdb, code2),
        where_clause = "STATEFP = '06' And COUNTYFP = '059'"
    )

arcpy.management.Copy(
    in_data=os.path.join(scratch_gdb, fc),
    out_data=os.path.join(tl_gdb, code),
    data_type="FeatureClass",
    associated_data=None
)


arcpy.ListFeatureClasses(tl_gdb)